### ISSUE TITLE
[Bug][Feature] Move compiler giving a warning or error for unknown attributes

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#9610] opened 2023-08-10 22:18 UTC
# 🐛 Bug

The Move compiler currently ignores unknown attributes. For example, the following code uses `#[testonly]` which is a typo of `#[test_only]`. This can leak some test-only code into the production.

https://github.com/aptos-labs/aptos-core/blob/9773481c1490debffcf1e6476754065ec9127ec4/aptos-move/framework/aptos-stdlib/sources/math64.move#L254

```
#[testonly]
    /// For functions that approximate a value it's useful to test a value is close
    /// to the most correct value up to last digit
    fun assert_approx_the_same(x: u128, y: u128, precission: u64) {
        if (x < y) {
            let tmp = x;
            x = y;
            y = tmp;
        };
        let mult = (pow(10, precission) as u128);
        assert!((x - y) * mult < x, 0);
    }
```

**Comment by brmataptos** [comment] 2023-08-11 00:00
This redundant with https://github.com/aptos-labs/aptos-core/issues/8875

**Comment by brmataptos** [comment] 2023-08-11 00:01
duplicate of https://github.com/aptos-labs/aptos-core/issues/8875.

**Closed by brmataptos** 2023-08-11 00:01 UTC
Labels: bug
