### ISSUE TITLE
Indexer - invalid or out-of-range datetime

### ISSUE THREAD

**Issue by olton** [aptos-labs/aptos-core#601] opened 2022-04-22 09:09 UTC
Hey! When I run indexer, I receive an error on height `31047`
```
2022-04-22T09:03:09.183501Z [main] INFO ecosystem/indexer/src/main.rs:100 Indexer has processed 31047 versions
```
```
thread 'tokio-runtime-worker' panicked at 'invalid or out-of-range datetime', /home/olton/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/naive/datetime.rs:117:18
```
And the indexer stop working.

**Comment by davidiw** [comment] 2022-06-29 00:49
status?

**Comment by CapCap** [comment] 2022-08-04 04:23
Closing as duplicate of #2442

**Closed by CapCap** 2022-08-04 04:23 UTC
Labels: bug
