### ISSUE TITLE
Indexer (chain_id 21, from version 2352555) invalid or out-of-range datetime

### ISSUE THREAD

**Issue by olton** [aptos-labs/aptos-core#2442] opened 2022-08-02 11:33 UTC
# 🐛 Bug

```
2022-08-02T11:11:33.441687Z [main] INFO ecosystem/indexer/src/indexer/tailer.rs:152 Will start fetching from version 2352555
2022-08-02T11:11:33.441712Z [main] INFO ecosystem/indexer/src/indexer/tailer.rs:91 Checking for previously errored versions...
2022-08-02T11:11:33.735492Z [tokio-runtime-worker] INFO ecosystem/indexer/src/indexer/tailer.rs:99 Found 1 previously errored versions for default_processor
thread 'tokio-runtime-worker' panicked at 'invalid or out-of-range datetime', /home/olton/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/naive/datetime.rs:117:18
```

## To reproduce

Run indexer

I use command to run
```
cargo run -- --pg-uri "postgresql://indexer:xxx@localhost/indexer" --node-url "https://fullnode.devnet.aptoslabs.com" --emit-every 25 --batch-size 100
```

**Comment by CapCap** [comment] 2022-08-04 04:22
Hey Olton, can you try with the indexer after #2419 please? Should be fixed :-)

**Comment by olton** [comment] 2022-08-04 09:45
```
olton@aptos-mirohost:~/aptos-core/ecosystem/indexer$ cargo run -- --pg-uri "postgresql://indexer:xxx@localhost/indexer" --node-url "https://fullnode.devnet.aptoslabs.com" --emit-every 25 --batch-size 100
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `/home/olton/aptos-core/target/debug/aptos-indexer --pg-uri 'postgresql://indexer:Gd6gfbJr867RF@localhost/indexer' --node-url 'https://fullnode.devnet.aptoslabs.com' --emit-every 25 --batch-size 100`
2022-08-04T09:43:25.367911Z [main] INFO ecosystem/indexer/src/main.rs:72 Starting indexer...
2022-08-04T09:43:25.394715Z [main] INFO ecosystem/indexer/src/main.rs:75 Created the connection pool...
2022-08-04T09:43:25.400545Z [main] INFO ecosystem/indexer/src/indexer/tailer.rs:77 Running migrations...
2022-08-04T09:43:25.401880Z [main] INFO ecosystem/indexer/src/indexer/tailer.rs:86 Migrations complete!
2022-08-04T09:43:25.401932Z [main] INFO ecosystem/indexer/src/indexer/tailer.rs:91 Checking if chain id is correct
thread 'main' panicked at 'ledger info must be present: error decoding response body: invalid type: integer `8`, expected a string at line 1 column 24

Caused by:
    invalid type: integer `8`, expected a string at line 1 column 24', ecosystem/indexer/src/indexer/fetcher.rs:43:14
```

**Comment by bowenyang007** [comment] 2022-08-04 17:37
@olton Ah actually the issue is that we've changed the type of LedgerInfo. LedgerInfo.epoch used to be int and is now string hence parsing fails. This will be resolved when we release devnet today. If you index test faucet it would work.

**Closed by bowenyang007** 2022-08-04 17:37 UTC
Labels: bug
