### ISSUE TITLE
[Bug] Inline functions should support struct fields

### ISSUE THREAD

**Issue by WGB5445** [aptos-labs/aptos-core#9355] opened 2023-07-28 01:31 UTC
# 🐛 Bug

In the inline function of Vec, I tried to use for_each to implement my function function, but found that the structure field cannot be accessed when traversing

## Code
```
module 0x1::test {

    use std::vector;
    use aptos_std::debug;

    struct T has drop{
        amount : u8
    }

    fun test(_account: &signer){
        let vec = vector::empty<T>();
        vector::for_each_ref(&vec, | e | debug::print(&e.amount));
    }
}

```
## When executing compile
```
error[E04010]: cannot infer type
   ┌─ /home/code/temp_code/sources/test.move:12:56
   │
12 │         vector::for_each_ref(&vec, | e | debug::print(&e.amount));
   │                                      -                 ^^^^^^^^ Unbound field 'amount'
   │                                      │                  
   │                                      Could not infer the type before field access. Try annotating here

{
  "Error": "Move compilation failed: Compilation error"

```

## Try adding type
```
module 0x1::test {

    use std::vector;
    use aptos_std::debug;

    struct T has drop{
        amount : u8
    }

    fun test(_account: &signer){
        let vec = vector::empty<T>();
        vector::for_each_ref(&vec, | e:&T | debug::print(&e.amount));
    }
}
```
```
error[E01002]: unexpected token
   ┌─ /home/code/temp_code/sources/test.move:12:39
   │
12 │         vector::for_each_ref(&vec, | e:&T | debug::print(&e.amount));
   │                                    -  ^ Expected '|'
   │                                    │   
   │                                    To match this '|'

{
  "Error": "Move compilation failed: Compilation error"
}

```

**Please complete the following information:**
- Aptos CLI 2.0.2
- Manjaro Linux

**Comment by wrwg** [comment] 2023-07-28 04:01
This is a duplicate of #6922. A workaround is to use 

```
foreach_ech_ref(&vec, |e| { let e:&T; print(&e.amount) })
```

**Comment by wrwg** [comment] 2023-07-28 04:02
> This is a duplicate of #6922. A workaround is to use
> 
> ```
> foreach_ech_ref(&vec, |e| { let e:&T; print(&e.amount) })
> ```

Correction:

```
foreach_ech_ref(&vec, |e| { let e:&T = e; print(&e.amount) })
```

**Closed by wrwg** 2023-07-28 04:01 UTC
Labels: bug
