### ISSUE TITLE
[Bug] Compiler errors on move test with empty source directory

### ISSUE THREAD

**Issue by chuacw** [aptos-labs/aptos-core#8974] opened 2023-07-06 04:13 UTC
# 🐛 Bug

An empty project, with no source at all, succeeds in aptos move compile but throws an error in aptos move test.

## To reproduce

**Code snippet to reproduce**
```
mkdir new_dir
chdir new_dir
aptos move init --name learning
aptos move test
```

**Stack trace/error message**
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', third_party\move\move-compiler\src\to_bytecode\context.rs:204:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

![image](https://github.com/aptos-labs/aptos-core/assets/1757930/0cbb1e80-b7e2-4aa8-90f6-ff763166419e)

## Expected Behavior

No error

## System information

    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "false",
    "build_commit_hash": "83250343e09f10e56f6ddbd8019f6d4634488349",
    "build_is_release_build": "true",
    "build_os": "windows-x86_64",
    "build_pkg_version": "2.0.1",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-pc-windows-msvc",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-06-05 18:04:18 +00:00",
    "build_using_tokio_unstable": "true"

## Additional context
It also errors on this simple source:
```
module 0x42::learning {
    #[test]
    use std::debug;

    struct Person has drop { //Has drop means can be deleted
        age: u8
    }

    public fun set_age(new_age: u8): u8 {
        let person = Person {age: new_age};
        person.age
    }

    #[test]
    fun test_set_age(){
        let age = set_age(10);
        debug::print(&age);
    }

}
```

**Comment by brmataptos** [comment] 2023-07-06 17:28
I think this is the same as https://github.com/aptos-labs/aptos-core/issues/8516 which was fixed in https://github.com/aptos-labs/aptos-core/pull/8867 which was landed 3 dyas ago: merged commit ea19ce1 into main [3 days ago](https://github.com/aptos-labs/aptos-core/pull/8867#event-9715101994).

**Comment by brmataptos** [comment] 2023-07-06 17:56
I followed the steps above using current code and it completed successfully.

**Comment by brmataptos** [comment] 2023-07-06 20:15
Ok, closing as a duplicate of https://github.com/aptos-labs/aptos-core/issues/8516 which was fixed in https://github.com/aptos-labs/aptos-core/pull/8867 which was landed 3 dyas ago: merged commit https://github.com/aptos-labs/aptos-core/commit/ea19ce1b272e5e2e979057bd58990e76e6c4d03a into main https://github.com/aptos-labs/aptos-core/pull/8867#event-9715101994.

**Closed** 2023-07-06 20:15 UTC
Labels: bug, needs-more-info
