### ISSUE TITLE
[Bug] Build Failure

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#10325] opened 2023-09-30 13:28 UTC
```
error[E0597]: `dst` does not live long enough
   --> /aptos/aptos-core/aptos-move/framework/src/natives/cryptography/bulletproofs.rs:195:41
    |
174 |     dst: Vec<u8>,
    |     --- binding `dst` declared here
...
195 |     let mut ver_trans = Transcript::new(dst.as_slice());
    |                         ----------------^^^^-
    |                         |               |
    |                         |               borrowed value does not live long enough
    |                         argument requires that `dst` is borrowed for `'static`
...
208 | }
    | - `dst` dropped here while still borrowed

```
https://github.com/aptos-labs/aptos-core/blob/b55cda2c934242fdbe9f3c564bc3670455ffbc83/aptos-move/framework/src/natives/cryptography/bulletproofs.rs#L194

Currently dirty fix workaround is `let mut ver_trans = Transcript::new(Box::leak(dst.into_boxed_slice()));` to passthough the compile however it possible to cause memory leak now. Please someone to figure out why `merlic::Transcript` is require "&static" argument or solve the compile error. I am using Rust Aptos SDK to programming my tools so I think this workaround will not affect to me.

I am now using newest rustc version: `rustc 1.74.0-nightly (8ce4540bd 2023-09-29)`

ChatGPT ver:

> Issue Title: "Compile Error: 'dst' Lifetime Issue in aptos-core - rustc 1.74.0-nightly"

> Description: 
> I encountered a compile error with rustc version 1.74.0-nightly while working on the Rust Aptos SDK. The error message indicates that `'dst'` does not live long enough in the `bulletproofs.rs` file. The issue seems to be related to the `merlic::Transcript` requiring a `'static` argument. 

> I currently have a workaround in place, which is `let mut ver_trans = Transcript::new(Box::leak(dst.into_boxed_slice()));`. However, this workaround might potentially cause a memory leak. 

> I am seeking assistance in understanding why `merlic::Transcript` requires a `&'static` argument or finding a solution to resolve this compile error.

> Repository Link: [aptos-core](https://github.com/aptos-labs/aptos-core/blob/b55cda2c934242fdbe9f3c564bc3670455ffbc83/aptos-move/framework/src/natives/cryptography/bulletproofs.rs#L194)

> Rustc Version: rustc 1.74.0-nightly (8ce4540bd 2023-09-29)

**Comment by Alivers** [comment] 2023-11-04 11:38
Same issue. Any updates?

**Comment by gregnazario** [comment] 2023-11-13 21:52
Hello! You may have to add the patches from the Aptos-core repo directly to your repo as well:

See these lines: https://github.com/aptos-labs/aptos-core/blob/main/Cargo.toml#L746-L751

Let me know if that doesn't fix it

**Comment by gregnazario** [comment] 2023-11-13 21:53
This is a duplicate of https://github.com/aptos-labs/aptos-core/issues/9377

**Comment by gregnazario** [comment] 2023-11-13 22:05
I'm going to try to again reach out to the authors of Merlin, but for updates surrounding this, please checkout https://github.com/aptos-labs/aptos-core/issues/9377 for more details.

**Closed by gregnazario** 2023-11-13 22:05 UTC
