### ISSUE TITLE
[Feature Request] Support upgrading specific modules in a package

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#8115] opened 2023-05-09 12:33 UTC
Currently updating the package would require including the bytecode for all modules even if most of them don't change (updating 1-2 modules is very common). We should allow upgrading specific modules in a package. The entire package would still go through the verifier. As for updating the source code, if it's too hard to change the source code for those specific modules because they're kept in a vector, we can offer a separate standalone function for package owners to update source code.

**Comment by wrwg** [comment] 2023-05-09 14:40
This is a duplicate of https://github.com/aptos-labs/aptos-core/issues/6936, which is more general than this one. If you agree, lets close this here in favor of the older one.

**Closed** 2023-05-28 16:11 UTC
Labels: enhancement, move-framework
