### ISSUE TITLE
[APT-17] [Bug] Move compilation fails on macOS

### ISSUE THREAD

**Issue by qiwihui** [aptos-labs/aptos-core#5629] opened 2022-11-18 03:14 UTC
# 🐛 Bug

Move compilation fails on macOS. Not sure what happened.

## To reproduce

**Code snippet to reproduce**
```Move
module bridge::loopwhatever {

    fun loopwhatevers(): u64 {
        let i = 1;
        let sum = 0;
        while (i <= 18) {
            i = i + 1;
            sum = sum + i;
            if (sum <= 55) continue;
            return sum
        };
        0
    }

    #[test]
    fun test_loopwhatevers() {
        assert!(loopwhatevers() == 55, 1);
    }
}
```

```toml
[package]
name = 'bridge'
version = '1.0.0'

[addresses]
bridge = '0xbfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e'
```

**Stack trace/error message**
```
$ aptos move test
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY AptosToken
INCLUDING DEPENDENCY MoveStdlib
BUILDING bridge
Running Move unit tests
2022-11-18T03:08:34.438202Z ERROR  {"message":"[VM] Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!\nError: VMError { major_status: INVALID_LOOP_BREAK, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: bfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e, name: Identifier(\"loopwhatever\") }), indices: [(FunctionDefinition, 0)], offsets: [(FunctionDefinitionIndex(0), 8)] }"}
[ FAIL    ] 0xbfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e::loopwhatever::test_loopwhatevers

Test failures:

Failures in 0xbfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e::loopwhatever:

┌── test_loopwhatevers ──────
│ ITE: An unknown error was reported. Location: error[E11001]: test failure
│    ┌─ /Users/qiwihui/Development/smart/aptos/bridge/sources/loops.move:6:9
│    │  
│  3 │       fun loopwhatevers(): u64 {
│    │           ------------- In this function in 0xbfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e::loopwhatever
│    ·  
│  6 │ ╭         while (i <= 18) {
│  7 │ │             i = i + 1;
│  8 │ │             sum = sum + i;
│  9 │ │             if (sum <= 55) continue;
│ 10 │ │             return sum
│ 11 │ │         };
│    │ ╰─────────^
│ 
│ 
│ VMError (if there is one): VMError {
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     message: Some(
│         "Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!\nError: VMError { major_status: INVALID_LOOP_BREAK, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: bfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e, name: Identifier(\"loopwhatever\") }), indices: [(FunctionDefinition, 0)], offsets: [(FunctionDefinitionIndex(0), 8)] }",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: bfde7c12bd91e484fcf00ffcbd1cec51adc2d1cd84b5d4d4312c3eecea13af1e,
│             name: Identifier(
│                 "loopwhatever",
│             ),
│         },
│     ),
│     indices: [
│         (
│             FunctionDefinition,
│             0,
│         ),
│     ],
│     offsets: [
│         (
│             FunctionDefinitionIndex(0),
│             8,
│         ),
│     ],
│ }
└──────────────────

Test result: FAILED. Total tests: 1; passed: 0; failed: 1
{
  "Error": "Move unit tests failed"
}
```

## System information

- Aptos Core Version: 1.0.0
- Rust Version: rustc 1.66.0-nightly (ce7f0f1aa 2022-09-28)
- Computer OS: M1, 13.0 (22A380)

## Additional context

<sub>[APT-17](https://linear.app/aptoslabs/issue/APT-17/[bug]-move-compilation-fails-on-macos)</sub>

**Comment by gregnazario** [comment] 2022-12-21 06:36
@wrwg this is because Move doesn't handle returns within loops correctly right?

I believe this is a known issue, and the work around would be to do a break and a return.

**Comment by wrwg** [comment] 2022-12-21 17:30
Is this still reproducable at head? I thought this problem has been fixed in the Move compiler and bytecode checker.

**Closed** 2023-01-19 04:38 UTC
Labels: bug, linear
