### ISSUE TITLE
Is there an API that can subscribe to the specified event

### ISSUE THREAD

**Issue by alphabiz-se2** [aptos-labs/aptos-core#1830] opened 2022-07-08 08:01 UTC
I am developing a module about transaction, which contains multiple steps, so it needs multiple requests to complete, but I can't get the real-time status of this transaction.

I released a move module, which provides interfaces similar to the following

- `request`: Create and store their `Transaction` move resource for current transaction, and send `RequestEvent` to request a new transaction
- `send`: Modify the current `Transaction` resource according to the business logic, and send the `SentEvent` to indicate that the transaction has been processed
- `receive`: Modify the current `Transaction` resource to change its status to "finished", and send a `ReceivedEvent` to indicate that the requester has received the information

The following is an example:

1. Bob is waiting for `RequestEvent`
2. Alice emit `RequestEvent` by calling `request`
3. Alice is waiting for `SentEvent`
4. Bob received `RequestEvent`
5. Bob emit `SentEvent` by calling `send`
6. Bob is waiting for `ReceivedEvent`
8. Alice received `SentEvent`
9. Alice emit `ReceivedEvent` by calling `receive`
10. Bob received `ReceivedEvent`

But I didn't find any API for subscribing to events

**Comment by gregnazario** [comment] 2022-07-25 21:10
There isn't currently support for event streaming e.g. SSE or Websockets.  I'm closing this as a duplicate of https://github.com/aptos-labs/aptos-core/issues/1940

**Closed by gregnazario** 2022-07-25 21:10 UTC
