### ISSUE TITLE
[Bug] When splitting up modules, each modules in a package pulls in the aptos-core dependency

### ISSUE THREAD

**Issue by mutable-dev** [aptos-labs/aptos-core#6178] opened 2023-01-12 20:45 UTC
# 🐛 Bug

Compilation taking much longer than expected after having split modules up due to max tx size exceeded errors when deploying

## To reproduce
- split a module into multiple submodules that need to important aptos-core

<img width="484" alt="image" src="https://user-images.githubusercontent.com/100337801/212177917-682a1631-aeb8-492c-a394-8a10afc1c28d.png">

## Expected Behavior

Aptos-core should not need to be used, we should be able to compile without pulling in dependencies

## System information

**Please complete the following information:**
- 1.0.3
- MacOs

## Additional context
- @gregnazario has the context

**Comment by gregnazario** [comment] 2023-01-23 15:30
This likely needs more digging, it's supposed to cache once as long as they all use the same branch

**Comment by wrwg** [comment] 2023-02-16 02:04
Duplicate of #5279

**Closed by wrwg** 2023-02-16 02:04 UTC
Labels: bug, move-cli
