### ISSUE TITLE
[Bug] Provide argument for dev-addresses in Aptos CLI

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5329] opened 2022-10-27 18:12 UTC
From Discord:
https://discord.com/channels/945856774056083548/1034215378299133974/1035252890824081459
---
Got some more feedback for y'all re: some low entry developer questions I've seen a bit in discord without answer.

Most move tutorials (albeit outside of the Aptos official ones) utilize [dev-addresses]. There's even 2 references within the aptos-core repo e2e tests that have definitions for them.

However it is impossible to utilize them with the aptos cli (because you can't provide -d or --dev through it. 

Allowing developers to quickly resolve this question would be helpful for them, as it is not intuitive to set up the move cli and resolve aptos vs move cli build dependency errors.
---

I am asking Greg to advise.

**Comment by wrwg** [comment] 2022-10-27 18:50
Duplicate of #5051

**Closed** 2022-10-27 18:50 UTC
Labels: bug, documentation
