### ISSUE TITLE
[Feature Request] Allow aptos move publish to cherry pick on specific module

### ISSUE THREAD

**Issue by 0xjinn** [aptos-labs/aptos-core#8327] opened 2023-05-23 03:16 UTC
# 🚀 Feature Request

Currently when you do `aptos move publish`, there is no way to upload only specific module. Instead the whole package get published

## Motivation

**Is your feature request related to a problem? Please describe.**

If there are multiple module in a package, and you do not want to publish the whole thing. The only way right now from CLI, is to create a package that contains only the module needed. This is too much overhead.

## Pitch

**Describe the solution you'd like**

The user should be able to publish specific module from the package. For example
`aptos move publish --module=my_module`

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by wrwg** [comment] 2023-05-30 22:53
Duplicate of https://github.com/aptos-labs/aptos-core/issues/6936

**Closed by wrwg** 2023-05-30 22:53 UTC
Labels: enhancement
