### ISSUE TITLE
[Bug] Code Example Links outdated

### ISSUE THREAD

**Issue by daweth** [aptos-labs/aptos-core#4130] opened 2022-09-12 22:42 UTC
# 🐛 Bug

Code example links are outdated on the aptos.dev website

## Steps to reproduce

https://aptos.dev/tutorials/your-first-dapp/

- Click on "full source code is available here"

## Expected Behavior

Should link to the correct example code

**Comment by ChengYueJia** [comment] 2022-09-15 09:05
@daweth The demo is outdated, It's removed. 

The new one isn't scheduled. 

So, I add the older demo in the docs.

Help this can help u.

**Comment by geekflyer** [comment] 2022-11-07 07:07
related/potential duplicate of #3700

**Closed** 2022-11-09 18:42 UTC
Labels: bug, community
