### ISSUE TITLE
[Feature Request] On-Chain Query with function

### ISSUE THREAD

**Issue by babyface001** [aptos-labs/aptos-core#5365] opened 2022-10-31 11:38 UTC
# 🚀 Feature Request

query data with functions 
## Motivation

now we can only query storage.

can we query data like ethereum eth_call

**Comment by babyface001** [comment] 2022-10-31 11:40
the biggst problem now is we must implement some algorithm with move and js.

**Comment by gregnazario** [comment] 2022-12-21 07:12
Duplicate of view functions https://github.com/aptos-labs/aptos-core/issues/4915

**Closed by gregnazario** 2022-12-21 07:12 UTC
Labels: enhancement, community
