### ISSUE TITLE
[operational-tooling] revamp it for aptos-framework

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#295] opened 2022-03-23 17:47 UTC
operational-tooling test suites in smoke-test is disabled during the migration to aptos-framework. AptosFramework will have a different staking based validator system, after that we should bring back those tooling

**Comment by davidiw** [comment] 2022-03-31 03:39
Merging #317 here

**Comment by davidiw** [comment] 2022-04-12 03:58
This is also duplicate of https://github.com/aptos-labs/aptos-core/issues/84

**Closed by davidiw** 2022-04-12 03:58 UTC
Labels: enhancement
