### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Abidouz** [aptos-labs/aptos-core#14859] opened 2024-10-03 06:11 UTC
New request: can Aptos employ blockchain innovations like Block-STM and a modular network design to achieve excellent blockchain scalability. The focus on improving transaction speed without compromising on security or functionality underlines the platform's commitment to smart contract functionality and blockchain innovation.

**Comment by georgemitenkov** [comment] 2024-11-11 22:29
Closing because the issue is not clear

**Closed by georgemitenkov** 2024-11-11 22:29 UTC
Labels: enhancement
