### ISSUE TITLE
Can I get the publickey of an address in Move module?

### ISSUE THREAD

**Issue by passer-byzhang** [aptos-labs/aptos-core#6639] opened 2023-02-16 09:53 UTC
## ❓ Questions and Help

If I pass a `vector<u8>` which is signed by a privateKey, I can use the `ed25519::signature_verify_strict` to verify the signer by its publicKey. 
How can I make sure the public key and address are the same account?

**Comment by honehone12** [comment] 2023-02-16 11:33
You can compute authentication key from public key.
https://aptos.dev/concepts/accounts#single-signer-authentication
And get authentication key of address by calling account::get_authentication_key.
 https://github.com/aptos-labs/aptos-core/blob/d4a859bb0987f8e35e7471469c3bcd4ae4b49855/aptos-move/framework/aptos-framework/doc/account.md#function-get_authentication_key
Then, check they are same.
May be I'm wrong. I did not tested, please test your own.

**Comment by gregnazario** [comment] 2023-03-20 06:18
Duplicate of https://github.com/aptos-labs/aptos-core/issues/6581#issue-1584661276

you can do it manually with the cli `aptos account lookup-address`

**Closed by gregnazario** 2023-03-20 06:18 UTC
